project_name: accessory
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: accessory
    ldflags:
      - -s -w
      - -X github.com/masaushi/accessory/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: masaushi
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

checksum:
  name_template: "checksum.txt"

release:
  prerelease: auto
