// Code generated by accessory; DO NOT EDIT.

package foo

import (
	"time"
)

func (t *Tester) Time() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.time
}

func (t *Tester) SetTime(val time.Time) {
	if t == nil {
		return
	}
	t.time = val
}
