// Code generated by accessory; DO NOT EDIT.

package test

func (tester *Tester) Field1() string {
	if tester == nil {
		return ""
	}
	return tester.field1
}

func (tester *Tester) SetSecondField(val int32) {
	tester.field2 = val
}

