// Code generated by accessory; DO NOT EDIT.

package test

func (t *Tester) SetField1(val string) {
	if t == nil {
		return
	}
	t.field1 = val
}

func (t *Tester) SetSecondField(val int32) {
	if t == nil {
		return
	}
	t.field2 = val
}

