// Code generated by accessory; DO NOT EDIT.

package test

func (t Tester) Field1() string {
	return t.field1
}

func (t Tester) Field2() int32 {
	return t.field2
}

func (t *Tester) SetField2(val int32) {
	if t == nil {
		return
	}
	t.field2 = val
}

func (t Tester) GetFieldThree() *bool {
	return t.field3
}

