// Code generated by accessory; DO NOT EDIT.

package test

func (t *Tester) GetField1() string {
	if t == nil {
		return ""
	}
	t.lock.RLock()
	defer t.lock.RUnlock()
	return t.field1
}

func (t *Tester) SetField1(val string) {
	if t == nil {
		return
	}
	t.lock.Lock()
	defer t.lock.Unlock()
	t.field1 = val
}

func (t *Tester) GetField2() int32 {
	if t == nil {
		return 0
	}
	t.lock.RLock()
	defer t.lock.RUnlock()
	return t.field2
}

func (t *Tester) SetField2(val int32) {
	if t == nil {
		return
	}
	t.lock.Lock()
	defer t.lock.Unlock()
	t.field2 = val
}

