// Code generated by accessory; DO NOT EDIT.

package test

func (t *Tester) Field1() string {
	if t == nil {
		return ""
	}
	return t.field1
}

func (t *Tester) SetSecondField(val int32) {
	t.field2 = val
}

